version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: focal-tibetan
      POSTGRES_PASSWORD: focal-tibetan
      POSTGRES_DB: focal-tibetan
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
