<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>QObject</name>
    <message>
        <source>Fri</source>
        <translation>周五</translation>
    </message>
    <message>
        <source>Mon</source>
        <translation>周一</translation>
    </message>
    <message>
        <source>Sat</source>
        <translation>周六</translation>
    </message>
    <message>
        <source>Sun</source>
        <translation>周日</translation>
    </message>
    <message>
        <source>Thu</source>
        <translation>周四</translation>
    </message>
    <message>
        <source>Tue</source>
        <translation>周二</translation>
    </message>
    <message>
        <source>Wed</source>
        <translation>周三</translation>
    </message>
    <message>
        <source>hour</source>
        <translation>小时</translation>
    </message>
    <message>
        <source>Only this shutdown</source>
        <translation>仅本次关机</translation>
    </message>
    <message>
        <source>hours</source>
        <translation>时</translation>
    </message>
    <message>
        <source>never</source>
        <translation>从不</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <source>time-shutdown</source>
        <translation>定时关机</translation>
    </message>
    <message>
        <source>minute</source>
        <translation>分</translation>
    </message>
    <message>
        <source>Confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <source>time-shutdown is already running!</source>
        <translation>定时关机已经运行</translation>
    </message>
    <message>
        <source>next shutdown</source>
        <translation>距离下一次关机时间</translation>
    </message>
    <message>
        <source>Everyday</source>
        <translation>每天</translation>
    </message>
    <message>
        <source>Shutdown</source>
        <translation>关机频率</translation>
    </message>
</context>
<context>
    <name>Widget</name>
    <message>
        <source>&amp;Quit</source>
        <translation>退出</translation>
    </message>
    <message>
        <source>never</source>
        <translation>从不</translation>
    </message>
    <message>
        <source>no set shutdown</source>
        <translation>未设置关机频率</translation>
    </message>
    <message>
        <source>&amp;Restore</source>
        <translation>打开</translation>
    </message>
    <message>
        <source>Mi&amp;nimize</source>
        <translation>最小化</translation>
    </message>
    <message>
        <source>warning</source>
        <translation>警告</translation>
    </message>
</context>
<context>
    <name>VerticalScroll_60</name>
    <message>
        <source>VerticalScroll_60</source>
        <translation></translation>
    </message>
</context>
</TS>
